---
- name: Web infrastructure deployment
  block:
    - name: Create web directories structure
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'
      loop: "{{ web_directories }}"
      tags: directories

    - name: Deploy site content
      block:
        - name: Install site1 content
          ansible.builtin.template:
            src: site1_index.html.j2
            dest: "{{ web_root }}/site1/index.html"
            owner: www-data
            group: www-data
            mode: 0644

        - name: Install site2 content
          ansible.builtin.template:
            src: site2_index.html.j2
            dest: "{{ web_root }}/site2/index.html"
            owner: www-data
            group: www-data
            mode: 0644

        - name: Create main portal page
          ansible.builtin.template:
            src: main_page.html.j2
            dest: "{{ web_root }}/main/index.html"
            owner: www-data
            group: www-data
            mode: 0644
      tags: content

- name: Nginx configuration
  block:
    - name: Install Nginx package
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: yes
      tags: nginx
      become: yes

    - name: Create Nginx config directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: 0755
      loop:
        - /etc/nginx/sites-available
        - /etc/nginx/sites-enabled
      tags: nginx
      become: yes

    - name: Remove default Nginx site
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/nginx/sites-enabled/default
        - /etc/nginx/sites-available/default
      tags: nginx
      become: yes

    - name: Check current nginx.conf include directive
      ansible.builtin.shell: grep -n "include.*sites-enabled" /etc/nginx/nginx.conf || true
      register: nginx_include_check
      changed_when: false
      tags: nginx
      become: yes

    - name: Update Nginx main config
      ansible.builtin.lineinfile:
        path: /etc/nginx/nginx.conf
        regexp: '^\s*include\s+/etc/nginx/sites-enabled/\*.*'
        line: '        include /etc/nginx/sites-enabled/*.conf;'
        backrefs: no
      notify: Reload Nginx
      tags: nginx
      become: yes

    - name: Debug nginx.conf before cleanup
      ansible.builtin.shell: grep -n "default.conf\|sites-enabled" /etc/nginx/nginx.conf || true
      register: nginx_debug_before
      changed_when: false
      tags: nginx
      become: yes

    - name: Display nginx.conf include directives before cleanup
      ansible.builtin.debug:
        var: nginx_debug_before.stdout_lines
      tags: nginx

    - name: Remove any default.conf references (improved)
      ansible.builtin.lineinfile:
        path: /etc/nginx/nginx.conf
        regexp: '^\s*include\s+/etc/nginx/sites-enabled/default\.conf;?\s*$'
        state: absent
      notify: Reload Nginx
      tags: nginx
      become: yes

    - name: Verify no default.conf references remain
      ansible.builtin.shell: grep -c "default\.conf" /etc/nginx/nginx.conf || echo "0"
      register: default_conf_count
      changed_when: false
      tags: nginx
      become: yes

    - name: Create empty default.conf as fallback
      ansible.builtin.file:
        path: "/etc/nginx/sites-available/default.conf"
        state: touch
        owner: root
        group: root
        mode: 0644
      when: default_conf_count.stdout != "0"
      tags: nginx
      become: yes

    - name: Enable default site fallback
      ansible.builtin.file:
        src: "/etc/nginx/sites-available/default.conf"
        dest: "/etc/nginx/sites-enabled/default.conf"
        state: link
      when: default_conf_count.stdout != "0"
      tags: nginx
      become: yes

    - name: Ensure only wildcard include exists
      ansible.builtin.lineinfile:
        path: /etc/nginx/nginx.conf
        regexp: '^\s*include\s+/etc/nginx/sites-enabled/\*\.conf;?\s*$'
        line: '        include /etc/nginx/sites-enabled/*.conf;'
        state: present
      notify: Reload Nginx
      tags: nginx
      become: yes

    - name: Debug nginx.conf after cleanup
      ansible.builtin.shell: grep -n "default.conf\|sites-enabled" /etc/nginx/nginx.conf || true
      register: nginx_debug_after
      changed_when: false
      tags: nginx
      become: yes

    - name: Display nginx.conf include directives after cleanup
      ansible.builtin.debug:
        var: nginx_debug_after.stdout_lines
      tags: nginx

    - name: Deploy default server configuration
      ansible.builtin.template:
        src: default.conf.j2
        dest: "/etc/nginx/sites-available/000-default.conf"
        owner: root
        group: root
        mode: 0644
      notify: Reload Nginx
      tags: nginx
      become: yes

    - name: Deploy virtual hosts configurations
      ansible.builtin.template:
        src: sites.conf.j2
        dest: "/etc/nginx/sites-available/{{ item }}.conf"
        owner: root
        group: root
        mode: 0644
      loop: "{{ nginx_domains }}"
      vars:
        domain: "{{ item }}"
      notify: Reload Nginx
      tags: nginx
      become: yes

    - name: Enable default site
      ansible.builtin.file:
        src: "/etc/nginx/sites-available/000-default.conf"
        dest: "/etc/nginx/sites-enabled/000-default.conf"
        state: link
      notify: Reload Nginx
      tags: nginx
      become: yes

    - name: Enable domain sites
      ansible.builtin.file:
        src: "/etc/nginx/sites-available/{{ item }}.conf"
        dest: "/etc/nginx/sites-enabled/{{ item }}.conf"
        state: link
      loop: "{{ nginx_domains }}"
      notify: Reload Nginx
      tags: nginx
      become: yes

- name: SSL management
  block:
    - name: Install Python OpenSSL dependencies
      ansible.builtin.apt:
        name: python3-openssl
        state: present
        update_cache: yes
      tags: ssl
      become: yes

    - name: Generate private key
      community.crypto.openssl_privatekey:
        path: /etc/ssl/private/selfsigned.key
        size: 4096
        type: RSA
        mode: 0600
        owner: root
        group: root
      tags: ssl
      become: yes

    - name: Create certificate signing request (CSR) for self-signed certificate
      community.crypto.openssl_csr_pipe:
        privatekey_path: /etc/ssl/private/selfsigned.key
        common_name: "{{ nginx_domains[0] }}"
        country_name: RU
        state_or_province_name: SPb
        locality_name: Saint-Petersburg
        organization_name: Example Org
        organizational_unit_name: IT Department
        subject_alt_name: "{{ nginx_domains | map('regex_replace', '^(.*)$', 'DNS:\\1') | list }}"
      register: csr
      tags: ssl
      become: yes

    - name: Generate unified certificate for all domains
      community.crypto.x509_certificate:
        path: /etc/ssl/certs/selfsigned.crt
        csr_content: "{{ csr.csr }}"
        privatekey_path: /etc/ssl/private/selfsigned.key
        provider: selfsigned
        selfsigned_digest: sha256
        selfsigned_not_after: "+365d"
        mode: 0644
        owner: root
        group: root
      tags: ssl
      notify: Reload Nginx
      become: yes

    - name: Verify certificate consistency
      ansible.builtin.shell: |
        openssl x509 -noout -modulus -in /etc/ssl/certs/selfsigned.crt | openssl md5
        openssl rsa -noout -modulus -in /etc/ssl/private/selfsigned.key | openssl md5
      register: cert_check
      changed_when: false
      tags: ssl

- name: Update Nginx SSL configuration
  block:
    - name: Configure SSL params without frame blocking
      ansible.builtin.template:
        src: ssl_params.conf.j2
        dest: /etc/nginx/snippets/ssl_params.conf
        owner: root
        group: root
        mode: 0644
      notify: Reload Nginx
      become: yes

    - name: Test Nginx configuration
      ansible.builtin.command: nginx -t
      register: nginx_test
      changed_when: false
      tags: nginx
      become: yes

    - name: Display Nginx test result
      ansible.builtin.debug:
        var: nginx_test.stdout
      tags: nginx
